"""Wrap the built dataset in a JS file so the site works from file:// and GitHub Pages."""
import json, os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
src = "data/parks.json"
dst = "data/data.js"
d = json.load(open(src, encoding="utf-8"))
with open(dst, "w", encoding="utf-8") as f:
    f.write("/* Generated by make_data_js.py - official data sources only. See data/parks.json */\n")
    f.write("window.__SG_PARK_DATA__=")
    json.dump(d, f, ensure_ascii=False, separators=(",", ":"))
    f.write(";\n")
print(dst, round(os.path.getsize(dst) / 1024), "KB |", len(d["parks"]), "parks")
print("sample:", d["parks"][0]["name"], "| sources:", len(d["meta"]["sources"]))
